#!/usr/bin/env node
/**
 * Builds every game in games/<id>/ and publishes it to public/g/<id>/.
 *
 * games/<id>/ is the ONE place a game's source lives. Nothing here is ever
 * hand-copied, and public/g/ is gitignored build output — which is what stops
 * the copies from drifting apart the way they did before.
 *
 * Adding a game: create games/<your-id>/ with a game.json and a Vite app.
 * Nothing else in the platform needs editing; the catalog picks it up.
 */
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const GAMES_DIR = path.join(ROOT, 'games');
const OUT_DIR = path.join(ROOT, 'public', 'g');
const REGISTRY = path.join(ROOT, 'src', 'lib', 'games.generated.ts');

const REQUIRED = ['id', 'name', 'description', 'category', 'minPlayers', 'maxPlayers'];
const CATEGORIES = ['puzzle', 'action', 'strategy', 'trivia', 'party'];

const only = process.argv.slice(2).find((a) => !a.startsWith('-'));
const skipBuild = process.argv.includes('--no-build');
/**
 * Write src/lib/games.generated.ts from the manifests and stop — no bundling,
 * no dist/ required. Typecheck and lint need that file to exist but don't care
 * about the bundles, and a cold checkout has neither.
 */
const registryOnly = process.argv.includes('--registry-only');

function log(msg) {
  console.log(`[games] ${msg}`);
}

function fail(msg) {
  console.error(`[games] ERROR ${msg}`);
  process.exit(1);
}

/** Read + validate a game.json so a bad game fails the build loudly, not silently at runtime. */
function readManifest(dir, id) {
  const file = path.join(dir, 'game.json');
  if (!fs.existsSync(file)) return null;

  let meta;
  try {
    meta = JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (e) {
    fail(`games/${id}/game.json is not valid JSON: ${e.message}`);
  }

  for (const key of REQUIRED) {
    if (meta[key] === undefined) fail(`games/${id}/game.json is missing "${key}"`);
  }
  if (meta.id !== id) {
    fail(`games/${id}/game.json has id "${meta.id}" but lives in games/${id}/ — they must match`);
  }
  if (!CATEGORIES.includes(meta.category)) {
    fail(`games/${id}/game.json category "${meta.category}" must be one of: ${CATEGORIES.join(', ')}`);
  }
  if (meta.minPlayers > meta.maxPlayers) {
    fail(`games/${id}/game.json has minPlayers > maxPlayers`);
  }
  return meta;
}

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const s = path.join(from, entry.name);
    const d = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function dirSize(dir) {
  let total = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    total += entry.isDirectory() ? dirSize(p) : fs.statSync(p).size;
  }
  return total;
}

if (!fs.existsSync(GAMES_DIR)) fail('games/ directory not found');

const ids = fs
  .readdirSync(GAMES_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory() && !e.name.startsWith('.'))
  .map((e) => e.name)
  .filter((id) => (only ? id === only : true));

if (only && ids.length === 0) fail(`no game named "${only}" in games/`);

const registry = [];

for (const id of ids) {
  const dir = path.join(GAMES_DIR, id);
  const meta = readManifest(dir, id);
  if (!meta) {
    log(`skip ${id} (no game.json)`);
    continue;
  }

  if (registryOnly) {
    registry.push(meta);
    continue;
  }

  const dest = path.join(OUT_DIR, id);

  if (!skipBuild) {
    if (!fs.existsSync(path.join(dir, 'node_modules'))) {
      log(`installing deps for ${id}…`);
      execSync('npm install', { cwd: dir, stdio: 'inherit' });
    }
    log(`building ${id}…`);
    // base=./ keeps the bundle working under any basePath, including the
    // /PlayBuddies/ prefix GitHub Pages serves from.
    execSync('npx vite build --base=./', { cwd: dir, stdio: 'inherit' });
  }

  const distDir = path.join(dir, 'dist');
  if (!fs.existsSync(distDir)) fail(`games/${id} produced no dist/ — did the build fail?`);

  fs.rmSync(dest, { recursive: true, force: true });
  copyDir(distDir, dest);

  // Publish the thumbnail next to the bundle so the catalog has one stable URL.
  if (meta.thumbnail) {
    const thumb = path.join(dir, meta.thumbnail);
    if (!fs.existsSync(thumb)) fail(`games/${id}: thumbnail "${meta.thumbnail}" not found`);
    fs.copyFileSync(thumb, path.join(dest, path.basename(meta.thumbnail)));
  }

  registry.push(meta);
  log(`${id} → public/g/${id}/  (${(dirSize(dest) / 1024).toFixed(0)} KB)`);
}

registry.sort((a, b) => Number(b.featured ?? 0) - Number(a.featured ?? 0) || a.name.localeCompare(b.name));

const generated = `// AUTO-GENERATED by scripts/build-games.mjs — do not edit.
// Edit games/<id>/game.json instead, then run: npm run build:games
import type { GameMetadata } from "@/types/game";

export const GENERATED_GAMES: GameMetadata[] = ${JSON.stringify(registry, null, 2)};
`;

fs.mkdirSync(path.dirname(REGISTRY), { recursive: true });
fs.writeFileSync(REGISTRY, generated);
log(
  `registry written: ${registry.length} game(s) → src/lib/games.generated.ts` +
    (registryOnly ? ' (registry only — bundles not built)' : ''),
);
