/**
 * The answers.
 *
 * Stored base64-encoded rather than as plain strings, and decoded once on
 * first use. This is deliberately NOT presented as security — anyone who
 * opens a console can decode it in one line. What it actually buys is that
 * the shipped bundle cannot be searched for the word on screen, which is the
 * realistic way somebody cheats at hangman in a browser: hit Ctrl+F, not
 * write a decoder.
 *
 * A serverless game cannot do better than this. Every client has to be able
 * to check a guessed letter on its own — that is what makes the whole match
 * replayable from its history and what removes any need for a resync path —
 * and checking a letter means holding the word. The only real fix is a
 * server that holds the answer and validates against it, which this platform
 * does not have.
 */

const PACKED: string[] = [
  "QU5LTEV8VGhlIEJvZHkKQU5URUxPUEV8QW5pbWFscwpBUkNIRVJZfFNwb3J0cyBhbmQgR2FtZXMKQVJDSElURUNUfEpvYnMKQVNU",
  "Uk9OQVVUfEpvYnMKQVZPQ0FET3xGb29kIGFuZCBEcmluawpCQURHRVJ8QW5pbWFscwpCQURNSU5UT058U3BvcnRzIGFuZCBHYW1l",
  "cwpCQUxDT05ZfEFyb3VuZCB0aGUgSG91c2UKQklTQ1VJVHxGb29kIGFuZCBEcmluawpCTEFDS1NNSVRIfEpvYnMKQkxBTktFVHxB",
  "cm91bmQgdGhlIEhvdXNlCkJMSVpaQVJEfE5hdHVyZSBhbmQgUGxhY2VzCkJPT0tTSEVMRnxBcm91bmQgdGhlIEhvdXNlCkJST0ND",
  "T0xJfEZvb2QgYW5kIERyaW5rCkJVVENIRVJ8Sm9icwpCVVRURVJGTFl8QW5pbWFscwpDQU5ZT058TmF0dXJlIGFuZCBQbGFjZXMK",
  "Q0FSQU1FTHxGb29kIGFuZCBEcmluawpDQVJQRU5URVJ8Sm9icwpDQVJQRVR8QXJvdW5kIHRoZSBIb3VzZQpDSEFNRUxFT058QW5p",
  "bWFscwpDSEVDS0VSU3xTcG9ydHMgYW5kIEdhbWVzCkNISU1ORVl8QXJvdW5kIHRoZSBIb3VzZQpDSE9DT0xBVEV8Rm9vZCBhbmQg",
  "RHJpbmsKQ0hPUlVTfE11c2ljIGFuZCBNb3ZpZXMKQ0lORU1BfE11c2ljIGFuZCBNb3ZpZXMKQ0lOTkFNT058Rm9vZCBhbmQgRHJp",
  "bmsKQ09NRURZfE11c2ljIGFuZCBNb3ZpZXMKQ1JPQ09ESUxFfEFuaW1hbHMKQ1JPSVNTQU5UfEZvb2QgYW5kIERyaW5rCkNVQ1VN",
  "QkVSfEZvb2QgYW5kIERyaW5rCkNVUEJPQVJEfEFyb3VuZCB0aGUgSG91c2UKQ1VSVEFJTnxBcm91bmQgdGhlIEhvdXNlCkRFTlRJ",
  "U1R8Sm9icwpERVNFUlR8TmF0dXJlIGFuZCBQbGFjZXMKREVURUNUSVZFfEpvYnMKRElSRUNUT1J8TXVzaWMgYW5kIE1vdmllcwpE",
  "T0xQSElOfEFuaW1hbHMKRE9NSU5PRVN8U3BvcnRzIGFuZCBHYW1lcwpET09SQkVMTHxBcm91bmQgdGhlIEhvdXNlCkRSQVdFUnxB",
  "cm91bmQgdGhlIEhvdXNlCkRSVU1NRVJ8TXVzaWMgYW5kIE1vdmllcwpEVU1QTElOR3xGb29kIGFuZCBEcmluawpFQVJUSFFVQUtF",
  "fE5hdHVyZSBhbmQgUGxhY2VzCkVMRUNUUklDSUFOfEpvYnMKRUxFUEhBTlR8QW5pbWFscwpFTkNPUkV8TXVzaWMgYW5kIE1vdmll",
  "cwpFU1BSRVNTT3xGb29kIGFuZCBEcmluawpFWUVCUk9XfFRoZSBCb2R5CkVZRUxBU0h8VGhlIEJvZHkKRkFMQ09OfEFuaW1hbHMK",
  "RklSRUZJR0hURVJ8Sm9icwpGSVJFUExBQ0V8QXJvdW5kIHRoZSBIb3VzZQpGTEFNSU5HT3xBbmltYWxzCkZSRUNLTEV8VGhlIEJv",
  "ZHkKRlJFRVpFUnxBcm91bmQgdGhlIEhvdXNlCkdJUkFGRkV8QW5pbWFscwpHTEFDSUVSfE5hdHVyZSBhbmQgUGxhY2VzCkdPQUxL",
  "RUVQRVJ8U3BvcnRzIGFuZCBHYW1lcwpHVUlUQVJ8TXVzaWMgYW5kIE1vdmllcwpHWU1OQVNUfFNwb3J0cyBhbmQgR2FtZXMKSEFS",
  "Qk9VUnxOYXR1cmUgYW5kIFBsYWNlcwpIQVJNT05ZfE11c2ljIGFuZCBNb3ZpZXMKSEVER0VIT0d8QW5pbWFscwpISUNDVVB8VGhl",
  "IEJvZHkKSFVSRExFU3xTcG9ydHMgYW5kIEdhbWVzCklDRUJFUkd8TmF0dXJlIGFuZCBQbGFjZXMKSkFOSVRPUnxKb2JzCkpBVkVM",
  "SU58U3BvcnRzIGFuZCBHYW1lcwpKRUxMWUZJU0h8QW5pbWFscwpKRVdFTExFUnxKb2JzCkpPVVJOQUxJU1R8Sm9icwpKVUdHTElO",
  "R3xTcG9ydHMgYW5kIEdhbWVzCkpVTkdMRXxOYXR1cmUgYW5kIFBsYWNlcwpLQU5HQVJPT3xBbmltYWxzCktBWUFLSU5HfFNwb3J0",
  "cyBhbmQgR2FtZXMKS0VUVExFfEFyb3VuZCB0aGUgSG91c2UKS0VZQk9BUkR8TXVzaWMgYW5kIE1vdmllcwpLSURORVl8VGhlIEJv",
  "ZHkKS05VQ0tMRXxUaGUgQm9keQpMQUdPT058TmF0dXJlIGFuZCBQbGFjZXMKTEFOVEVSTnxBcm91bmQgdGhlIEhvdXNlCkxBU0FH",
  "TkV8Rm9vZCBhbmQgRHJpbmsKTEFVTkRSWXxBcm91bmQgdGhlIEhvdXNlCkxBV1lFUnxKb2JzCkxFTU9OQURFfEZvb2QgYW5kIERy",
  "aW5rCkxFT1BBUkR8QW5pbWFscwpMSUJSQVJJQU58Sm9icwpMSUNPUklDRXxGb29kIGFuZCBEcmluawpMSUdIVE5JTkd8TmF0dXJl",
  "IGFuZCBQbGFjZXMKTE9CU1RFUnxBbmltYWxzCkxVTExBQll8TXVzaWMgYW5kIE1vdmllcwpNQVJBVEhPTnxTcG9ydHMgYW5kIEdh",
  "bWVzCk1BUk1BTEFERXxGb29kIGFuZCBEcmluawpNQVRUUkVTU3xBcm91bmQgdGhlIEhvdXNlCk1FQURPV3xOYXR1cmUgYW5kIFBs",
  "YWNlcwpNRUNIQU5JQ3xKb2JzCk1FUklOR1VFfEZvb2QgYW5kIERyaW5rCk1JQ1JPUEhPTkV8TXVzaWMgYW5kIE1vdmllcwpNSVJS",
  "T1J8QXJvdW5kIHRoZSBIb3VzZQpNT05HT09TRXxBbmltYWxzCk1PVU5UQUlOfE5hdHVyZSBhbmQgUGxhY2VzCk1VU0NMRXxUaGUg",
  "Qm9keQpNVVNIUk9PTXxGb29kIGFuZCBEcmluawpOT09ETEV8Rm9vZCBhbmQgRHJpbmsKTlVSU0V8Sm9icwpPQ1RPUFVTfEFuaW1h",
  "bHMKT01FTEVUVEV8Rm9vZCBhbmQgRHJpbmsKT1JDSEFSRHxOYXR1cmUgYW5kIFBsYWNlcwpPUkNIRVNUUkF8TXVzaWMgYW5kIE1v",
  "dmllcwpPU1RSSUNIfEFuaW1hbHMKUEFERExFfFNwb3J0cyBhbmQgR2FtZXMKUEFOQ0FLRXxGb29kIGFuZCBEcmluawpQQU5USEVS",
  "fEFuaW1hbHMKUEVOQUxUWXxTcG9ydHMgYW5kIEdhbWVzClBFTkdVSU58QW5pbWFscwpQSE9UT0dSQVBIRVJ8Sm9icwpQSUxMT1d8",
  "QXJvdW5kIHRoZSBIb3VzZQpQSUxPVHxKb2JzClBJTkVBUFBMRXxGb29kIGFuZCBEcmluawpQTFVNQkVSfEpvYnMKUE9QQ09STnxN",
  "dXNpYyBhbmQgTW92aWVzClBPUkNVUElORXxBbmltYWxzClBPUlJJREdFfEZvb2QgYW5kIERyaW5rClBSQUlSSUV8TmF0dXJlIGFu",
  "ZCBQbGFjZXMKUFJFVFpFTHxGb29kIGFuZCBEcmluawpRVUFSUll8TmF0dXJlIGFuZCBQbGFjZXMKUkFDQ09PTnxBbmltYWxzClJB",
  "RElBVE9SfEFyb3VuZCB0aGUgSG91c2UKUkFJTkJPV3xOYXR1cmUgYW5kIFBsYWNlcwpSQVNQQkVSUll8Rm9vZCBhbmQgRHJpbmsK",
  "UkVGRVJFRXxTcG9ydHMgYW5kIEdhbWVzClJIWVRITXxNdXNpYyBhbmQgTW92aWVzClNBSUxPUnxKb2JzClNBTkRXSUNIfEZvb2Qg",
  "YW5kIERyaW5rClNBWE9QSE9ORXxNdXNpYyBhbmQgTW92aWVzClNDSUVOVElTVHxKb2JzClNDT1JQSU9OfEFuaW1hbHMKU0VBU0hF",
  "TEx8TmF0dXJlIGFuZCBQbGFjZXMKU0VRVUVMfE11c2ljIGFuZCBNb3ZpZXMKU0hJVkVSfFRoZSBCb2R5ClNIT1VMREVSfFRoZSBC",
  "b2R5ClNLQVRFQk9BUkR8U3BvcnRzIGFuZCBHYW1lcwpTS0VMRVRPTnxUaGUgQm9keQpTTkVFWkV8VGhlIEJvZHkKU05PT0tFUnxT",
  "cG9ydHMgYW5kIEdhbWVzClNOT1JLRUx8U3BvcnRzIGFuZCBHYW1lcwpTT1VORFRSQUNLfE11c2ljIGFuZCBNb3ZpZXMKU1BBR0hF",
  "VFRJfEZvb2QgYW5kIERyaW5rClNQSU5FfFRoZSBCb2R5ClNQUklOVEVSfFNwb3J0cyBhbmQgR2FtZXMKU1FVSVJSRUx8QW5pbWFs",
  "cwpTVEFESVVNfFNwb3J0cyBhbmQgR2FtZXMKU1RBSVJDQVNFfEFyb3VuZCB0aGUgSG91c2UKU1RPTUFDSHxUaGUgQm9keQpTVUJU",
  "SVRMRXxNdXNpYyBhbmQgTW92aWVzClNVTlNFVHxOYXR1cmUgYW5kIFBsYWNlcwpTVVJHRU9OfEpvYnMKU1dBTVB8TmF0dXJlIGFu",
  "ZCBQbGFjZXMKVEFSQU5UVUxBfEFuaW1hbHMKVEVBQ0hFUnxKb2JzClRIUk9BVHxUaGUgQm9keQpUSFVNQnxUaGUgQm9keQpUSFVO",
  "REVSfE5hdHVyZSBhbmQgUGxhY2VzClRPQVNURVJ8QXJvdW5kIHRoZSBIb3VzZQpUT05HVUV8VGhlIEJvZHkKVE9SVE9JU0V8QW5p",
  "bWFscwpUUkFJTEVSfE11c2ljIGFuZCBNb3ZpZXMKVFJPUEhZfFNwb3J0cyBhbmQgR2FtZXMKVFJVTVBFVHxNdXNpYyBhbmQgTW92",
  "aWVzClRVTkRSQXxOYXR1cmUgYW5kIFBsYWNlcwpVTUJSRUxMQXxBcm91bmQgdGhlIEhvdXNlClZBQ1VVTXxBcm91bmQgdGhlIEhv",
  "dXNlClZJTExBSU58TXVzaWMgYW5kIE1vdmllcwpWSU5FR0FSfEZvb2QgYW5kIERyaW5rClZJT0xJTnxNdXNpYyBhbmQgTW92aWVz",
  "ClZPTENBTk98TmF0dXJlIGFuZCBQbGFjZXMKVk9MTEVZQkFMTHxTcG9ydHMgYW5kIEdhbWVzClZVTFRVUkV8QW5pbWFscwpXQUZG",
  "TEV8Rm9vZCBhbmQgRHJpbmsKV0FJVEVSfEpvYnMKV0FMUlVTfEFuaW1hbHMKV0FSRFJPQkV8QXJvdW5kIHRoZSBIb3VzZQpXQVRF",
  "UkZBTEx8TmF0dXJlIGFuZCBQbGFjZXMKV0hJUkxQT09MfE5hdHVyZSBhbmQgUGxhY2VzCldISVNQRVJ8VGhlIEJvZHkKV0lORE9X",
  "fEFyb3VuZCB0aGUgSG91c2UKV09PRFBFQ0tFUnxBbmltYWxzCldSRVNUTElOR3xTcG9ydHMgYW5kIEdhbWVzCldSSU5LTEV8VGhl",
  "IEJvZHkKWUFXTnxUaGUgQm9keQpZT0dIVVJUfEZvb2QgYW5kIERyaW5rClpFQlJBfEFuaW1hbHM=",
];

export interface Answer {
  /** Always A-Z, 4 to 12 letters, no spaces or punctuation. */
  word: string;
  /** Shown to everyone from the first turn. A hangman with no hint is a spelling test. */
  category: string;
}

let cache: Answer[] | null = null;

/** The whole list, decoded on first use and kept for the session. */
export function answers(): Answer[] {
  if (cache) return cache;
  const decoded = atob(PACKED.join(''));
  cache = decoded
    .split('\n')
    .map((line) => {
      const [word, category] = line.split('|');
      return { word, category };
    })
    .filter((a) => Boolean(a.word && a.category));
  return cache;
}

export const ANSWER_COUNT = () => answers().length;
